"""mdt tables

Revision ID: 8eca4622d09e
Revises: bd39170c3e32
Create Date: 2026-01-24 20:13:15.237722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eca4622d09e'
down_revision: Union[str, Sequence[str], None] = 'bd39170c3e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mdt_cad_sync_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('training_mode', sa.Boolean(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('dispatch_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['cad_calls.id'], ),
    sa.ForeignKeyConstraint(['dispatch_id'], ['cad_dispatches.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['cad_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mdt_cad_sync_events_call_id'), 'mdt_cad_sync_events', ['call_id'], unique=False)
    op.create_index(op.f('ix_mdt_cad_sync_events_dispatch_id'), 'mdt_cad_sync_events', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_mdt_cad_sync_events_id'), 'mdt_cad_sync_events', ['id'], unique=False)
    op.create_index(op.f('ix_mdt_cad_sync_events_org_id'), 'mdt_cad_sync_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_mdt_cad_sync_events_unit_id'), 'mdt_cad_sync_events', ['unit_id'], unique=False)
    op.create_table('mdt_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('training_mode', sa.Boolean(), nullable=True),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['cad_calls.id'], ),
    sa.ForeignKeyConstraint(['dispatch_id'], ['cad_dispatches.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['cad_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mdt_events_call_id'), 'mdt_events', ['call_id'], unique=False)
    op.create_index(op.f('ix_mdt_events_dispatch_id'), 'mdt_events', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_mdt_events_id'), 'mdt_events', ['id'], unique=False)
    op.create_index(op.f('ix_mdt_events_org_id'), 'mdt_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_mdt_events_unit_id'), 'mdt_events', ['unit_id'], unique=False)
    op.create_table('mdt_obd_ingests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('training_mode', sa.Boolean(), nullable=True),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('ignition_on', sa.Boolean(), nullable=True),
    sa.Column('lights_sirens_active', sa.Boolean(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('leg_mileage', sa.Float(), nullable=True),
    sa.Column('transport_distance', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['cad_calls.id'], ),
    sa.ForeignKeyConstraint(['dispatch_id'], ['cad_dispatches.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['cad_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mdt_obd_ingests_call_id'), 'mdt_obd_ingests', ['call_id'], unique=False)
    op.create_index(op.f('ix_mdt_obd_ingests_dispatch_id'), 'mdt_obd_ingests', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_mdt_obd_ingests_id'), 'mdt_obd_ingests', ['id'], unique=False)
    op.create_index(op.f('ix_mdt_obd_ingests_org_id'), 'mdt_obd_ingests', ['org_id'], unique=False)
    op.create_index(op.f('ix_mdt_obd_ingests_unit_id'), 'mdt_obd_ingests', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mdt_obd_ingests_unit_id'), table_name='mdt_obd_ingests')
    op.drop_index(op.f('ix_mdt_obd_ingests_org_id'), table_name='mdt_obd_ingests')
    op.drop_index(op.f('ix_mdt_obd_ingests_id'), table_name='mdt_obd_ingests')
    op.drop_index(op.f('ix_mdt_obd_ingests_dispatch_id'), table_name='mdt_obd_ingests')
    op.drop_index(op.f('ix_mdt_obd_ingests_call_id'), table_name='mdt_obd_ingests')
    op.drop_table('mdt_obd_ingests')
    op.drop_index(op.f('ix_mdt_events_unit_id'), table_name='mdt_events')
    op.drop_index(op.f('ix_mdt_events_org_id'), table_name='mdt_events')
    op.drop_index(op.f('ix_mdt_events_id'), table_name='mdt_events')
    op.drop_index(op.f('ix_mdt_events_dispatch_id'), table_name='mdt_events')
    op.drop_index(op.f('ix_mdt_events_call_id'), table_name='mdt_events')
    op.drop_table('mdt_events')
    op.drop_index(op.f('ix_mdt_cad_sync_events_unit_id'), table_name='mdt_cad_sync_events')
    op.drop_index(op.f('ix_mdt_cad_sync_events_org_id'), table_name='mdt_cad_sync_events')
    op.drop_index(op.f('ix_mdt_cad_sync_events_id'), table_name='mdt_cad_sync_events')
    op.drop_index(op.f('ix_mdt_cad_sync_events_dispatch_id'), table_name='mdt_cad_sync_events')
    op.drop_index(op.f('ix_mdt_cad_sync_events_call_id'), table_name='mdt_cad_sync_events')
    op.drop_table('mdt_cad_sync_events')
    # ### end Alembic commands ###
