"""
Fire MDT Database Models - Master Specification Implementation

This module implements the locked Fire MDT data model for GPS/OBD-derived
operational tracking without PSAP/CAD dependency.

All timestamps are MDT Unit/Vehicle times, never dispatch times.
"""

from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime, Text, JSON, ForeignKey, Enum as SQLEnum, Numeric, SmallInteger
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from datetime import datetime
from enum import Enum
import uuid
from core.database import Base


# ============================================================================
# ENUMS - Locked by Specification
# ============================================================================

class FireIncidentType(str, Enum):
    FIRE = "fire"
    MEDICAL_ASSIST = "medical_assist"
    RESCUE = "rescue"
    OTHER = "other"


class FireIncidentStatus(str, Enum):
    OPEN = "open"
    ACTIVE = "active"
    CLOSED = "closed"
    CANCELLED = "cancelled"


class FireIncidentPriority(str, Enum):
    EMERGENCY = "emergency"
    NON_EMERGENCY = "non_emergency"
    TRAINING = "training"


class TimelineEventType(str, Enum):
    """Locked event types - only these are valid"""
    MDT_INCIDENT_GENERATED = "mdt_incident_generated"
    UNIT_MOVING = "unit_moving"
    UNIT_STOPPED = "unit_stopped"
    ON_SCENE = "on_scene"
    DEPART_SCENE = "depart_scene"
    AT_DESTINATION = "at_destination"
    DEPART_DESTINATION = "depart_destination"
    RETURN_STATION = "return_station"
    INCIDENT_COMPLETED = "incident_completed"
    OBD_UNAVAILABLE = "obd_unavailable"
    GPS_MODE_ACTIVE = "gps_mode_active"


class TimelineEventSource(str, Enum):
    """Data provenance - locked"""
    MANUAL = "manual"
    OBD = "obd"
    GPS = "gps"
    GEOFENCE = "geofence"
    GPS_ONLY = "gps_only"
    MIXED = "mixed"


class GeofenceRole(str, Enum):
    """Geofence purpose - locked"""
    SCENE = "scene"
    DESTINATION = "destination"
    STATION = "station"
    COVERAGE = "coverage"


class OBDGear(str, Enum):
    """Vehicle gear state"""
    PARK = "park"
    DRIVE = "drive"
    REVERSE = "reverse"
    NEUTRAL = "neutral"
    UNKNOWN = "unknown"


# ============================================================================
# CORE TABLES - Authoritative
# ============================================================================

class FireIncident(Base):
    """
    Fire MDT Incident - Crew-initiated response tracking.
    
    This table stores incidents generated by MDT devices when crews press
    "Generate Incident". It does NOT represent dispatch/CAD incidents.
    
    All incidents start with manual crew action, not automatic detection.
    """
    __tablename__ = "fire_incidents"
    
    # Identity
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    org_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    station_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    unit_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    
    # Incident identity
    incident_number = Column(String, nullable=False, unique=True, index=True)
    incident_type = Column(SQLEnum(FireIncidentType), nullable=False, default=FireIncidentType.FIRE)
    priority = Column(SQLEnum(FireIncidentPriority), nullable=True)
    
    # Scene location (manually entered by crew)
    scene_address_text = Column(Text, nullable=False)
    scene_lat = Column(Numeric(10, 7), nullable=True)
    scene_lng = Column(Numeric(10, 7), nullable=True)
    scene_geofence_meters = Column(Integer, default=300)
    
    # Destination (optional)
    destination_name = Column(Text, nullable=True)
    destination_address_text = Column(Text, nullable=True)
    destination_lat = Column(Numeric(10, 7), nullable=True)
    destination_lng = Column(Numeric(10, 7), nullable=True)
    destination_geofence_meters = Column(Integer, default=300)
    
    # Status
    status = Column(SQLEnum(FireIncidentStatus), default=FireIncidentStatus.OPEN, nullable=False, index=True)
    
    # Lifecycle
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    closed_at = Column(DateTime, nullable=True)
    
    # Relationships
    timeline_events = relationship("FireIncidentTimeline", back_populates="incident", cascade="all, delete-orphan")


class FireIncidentTimeline(Base):
    """
    Fire MDT Timeline - Source of truth for all operational times.
    
    This table is the LOCKED timeline. All analytics, reports, and exports
    must derive from these events. Never compute times from other sources.
    
    Every state change creates a new row. Rows are immutable except for
    manual overrides (which create new rows with override_flag=true).
    """
    __tablename__ = "fire_incident_timeline"
    
    # Identity
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    org_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    incident_id = Column(UUID(as_uuid=True), ForeignKey("fire_incidents.id", ondelete="CASCADE"), nullable=False, index=True)
    unit_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    station_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    
    # Event data - AUTHORITATIVE
    event_type = Column(SQLEnum(TimelineEventType), nullable=False, index=True)
    event_time = Column(DateTime, nullable=False, index=True)  # The REAL time this happened
    received_time = Column(DateTime, default=datetime.utcnow, nullable=False)  # When server received it
    
    # Provenance - REQUIRED for defensibility
    source = Column(SQLEnum(TimelineEventSource), nullable=False)
    confidence = Column(SmallInteger, default=100)  # 0-100 confidence score
    
    # Location (if applicable)
    lat = Column(Numeric(10, 7), nullable=True)
    lng = Column(Numeric(10, 7), nullable=True)
    
    # Geofence context
    geofence_id = Column(UUID(as_uuid=True), nullable=True)
    geofence_role = Column(SQLEnum(GeofenceRole), nullable=True)
    
    # OBD linkage
    obd_snapshot_id = Column(UUID(as_uuid=True), nullable=True)
    
    # Override tracking
    override_flag = Column(Boolean, default=False, nullable=False)
    override_reason = Column(Text, nullable=True)
    
    # Audit
    notes = Column(Text, nullable=True)
    created_by_user_id = Column(UUID(as_uuid=True), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    incident = relationship("FireIncident", back_populates="timeline_events")


class MDTOBDIngest(Base):
    """
    MDT OBD Telemetry Ingest.
    
    Stores OBD-II data from vehicle ECU for state machine logic.
    Primary use: gear state (PARK/DRIVE) and speed for automatic
    state transitions.
    """
    __tablename__ = "mdt_obd_ingest"
    
    # Identity
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    org_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    unit_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    device_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    
    # Timing
    ingest_time = Column(DateTime, nullable=False, index=True)
    
    # OBD data (nullable - not all vehicles support all PIDs)
    speed_mph = Column(Numeric(5, 2), nullable=True)
    gear = Column(SQLEnum(OBDGear), nullable=True)
    ignition_on = Column(Boolean, nullable=True)
    odometer_miles = Column(Numeric(10, 2), nullable=True)
    engine_rpm = Column(Integer, nullable=True)
    fuel_level_pct = Column(Numeric(5, 2), nullable=True)
    
    # Raw payload for debugging
    raw_payload = Column(JSON, nullable=True)
    
    # Lifecycle
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class MDTGPSBreadcrumb(Base):
    """
    MDT GPS Breadcrumb Trail.
    
    Stores GPS location history for:
    - Geofence detection
    - Travel distance calculation
    - Fallback state transitions when OBD unavailable
    - Route replay and visualization
    """
    __tablename__ = "mdt_gps_breadcrumb"
    
    # Identity
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    org_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    unit_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    device_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    incident_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    
    # GPS data
    gps_time = Column(DateTime, nullable=False, index=True)
    lat = Column(Numeric(10, 7), nullable=False)
    lng = Column(Numeric(10, 7), nullable=False)
    
    # GPS metadata
    speed_mph = Column(Numeric(5, 2), nullable=True)
    heading = Column(Numeric(5, 2), nullable=True)  # 0-360 degrees
    accuracy_m = Column(Numeric(6, 2), nullable=True)  # Accuracy in meters
    altitude_m = Column(Numeric(8, 2), nullable=True)
    
    # Lifecycle
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class FireGeofence(Base):
    """
    Fire MDT Geofences.
    
    Defines circular geofences for automatic state detection:
    - Station geofences (return to station detection)
    - Scene geofences (on scene/depart scene)
    - Destination geofences (at destination)
    - Coverage area geofences (response zones)
    """
    __tablename__ = "fire_geofences"
    
    # Identity
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    org_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    station_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    
    # Geofence definition
    name = Column(String, nullable=False)
    role = Column(SQLEnum(GeofenceRole), nullable=False, index=True)
    center_lat = Column(Numeric(10, 7), nullable=False)
    center_lng = Column(Numeric(10, 7), nullable=False)
    radius_meters = Column(Integer, nullable=False)
    
    # Metadata
    active = Column(Boolean, default=True, nullable=False)
    notes = Column(Text, nullable=True)
    
    # Lifecycle
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class FireMDTDevice(Base):
    """
    Fire MDT Device Registry.
    
    Tracks MDT devices for token binding and audit.
    Each device has its own Keycloak client credential.
    """
    __tablename__ = "fire_mdt_devices"
    
    # Identity
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    org_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    unit_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    station_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    
    # Device info
    device_name = Column(String, nullable=False)
    device_serial = Column(String, nullable=True, unique=True)
    keycloak_client_id = Column(String, nullable=True, unique=True)
    
    # Capabilities
    obd_capable = Column(Boolean, default=False)
    gps_capable = Column(Boolean, default=True)
    
    # Status
    active = Column(Boolean, default=True, nullable=False)
    last_seen_at = Column(DateTime, nullable=True)
    
    # Lifecycle
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class FireMDTOfflineQueue(Base):
    """
    Fire MDT Offline Event Queue.
    
    Stores events captured offline for replay when connectivity restored.
    Uses client_event_id as idempotency key to prevent duplicates.
    """
    __tablename__ = "fire_mdt_offline_queue"
    
    # Identity
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    client_event_id = Column(UUID(as_uuid=True), nullable=False, unique=True, index=True)  # Idempotency key
    org_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    unit_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    device_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    
    # Event data
    event_type = Column(String, nullable=False)
    event_time = Column(DateTime, nullable=False)  # Original event time
    payload = Column(JSON, nullable=False)
    
    # Retry tracking
    retry_count = Column(Integer, default=0, nullable=False)
    last_attempt_time = Column(DateTime, nullable=True)
    processed = Column(Boolean, default=False, nullable=False, index=True)
    processed_at = Column(DateTime, nullable=True)
    
    # Error tracking
    last_error = Column(Text, nullable=True)
    
    # Lifecycle
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
